# -*- mode: python ; coding: utf-8 -*-

from project_config import APP_ICON_PATH, APP_TITLE


a = Analysis(
    ["app_fluent.py"],
    pathex=[],
    binaries=[],
    datas=[
        (str(APP_ICON_PATH), "assets"),
        ("data/schedule.json", "data"),
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "PyQt5",
        "PyQt6",
        "PySide2",
        "IPython",
        "PIL",
        "aiohttp",
        "cv2",
        "Cython",
        "gevent",
        "google",
        "grpc",
        "jedi",
        "jsonschema",
        "lxml",
        "matplotlib",
        "nbformat",
        "numpy",
        "onnx",
        "onnxruntime",
        "opentelemetry",
        "pandas",
        "pyarrow",
        "pygame",
        "pytest",
        "scipy",
        "sympy",
        "tkinter",
        "torch",
        "torchvision",
        "tornado",
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name=APP_TITLE,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(APP_ICON_PATH),
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name=APP_TITLE,
)
